# -*- coding: utf-8 -*-
"""
/***************************************************************************
 grip_tester
                                 A QGIS plugin
 plugin for processing grip tester readings
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-26
        copyright            : (C) 2020 by Drew
        email                : drew.bennett@ptsinternational.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load grip_tester class from file grip_tester.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .grip_tester import grip_tester
    return grip_tester(iface)
